config/routes.rb
AnimalIdentificationSystem::Application.routes.draw do
  get "index/index"
  resources :animal_behaviors

  root 'index#index'

end

app/models/animal_behavior.rb
class AnimalBehavior < ActiveRecord::Base
end

app/controllers/animal_behaviors_controller.rb
class AnimalBehaviorsController < ApplicationController
  before_action :set_animal_behavior, only: [:show, :edit, :update, :destroy]

  # GET /animal_behaviors
  # GET /animal_behaviors.json
  def index
    @animal_behaviors = AnimalBehavior.all
  end

  # GET /animal_behaviors/1
  # GET /animal_behaviors/1.json
  def show
  end

  # GET /animal_behaviors/new
  def new
    @animal_behavior = AnimalBehavior.new
  end

  # GET /animal_behaviors/1/edit
  def edit
  end

  # POST /animal_behaviors
  # POST /animal_behaviors.json
  def create
    @animal_behavior = AnimalBehavior.new(animal_behavior_params)

    respond_to do |format|
      if @animal_behavior.save
        format.html { redirect_to @animal_behavior, notice: 'Animal behavior was successfully created.' }
        format.json { render action: 'show', status: :created, location: @animal_behavior }
      else
        format.html { render action: 'new' }
        format.json { render json: @animal_behavior.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animal_behaviors/1
  # PATCH/PUT /animal_behaviors/1.json
  def update
    respond_to do |format|
      if @animal_behavior.update(animal_behavior_params)
        format.html { redirect_to @animal_behavior, notice: 'Animal behavior was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @animal_behavior.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animal_behaviors/1
  # DELETE /animal_behaviors/1.json
  def destroy
    @animal_behavior.destroy
    respond_to do |format|
      format.html { redirect_to animal_behaviors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal_behavior
      @animal_behavior = AnimalBehavior.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_behavior_params
      params.require(:animal_behavior).permit(:code, :behavior)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    @animal_behaviors = AnimalBehavior.all
    @checked_behaviors = params

    if is_mammal?
      @animal = "哺乳动物"
      if is_carnivore?
        @animal = "食肉动物"
        # IF该动物是食肉动物 AND是黄褐色 AND身上有黑色条纹 THEN该动物是老虎
        if is_carnivore? && params[:brown] && params[:black_stripes]
          @animal = "老虎"
        # IF该动物是肉食动物 AND是黄褐色 AND身上有黑色斑点 THEN该动物是金钱豹 
        elsif is_carnivore? && params[:brown] && params[:black_spots]
          @animal = "金钱豹"
        # IF该动物是有蹄类动物 AND有长脖子 AND有长腿 AND是黄褐色AND身上有暗斑点 THEN该动物是长颈鹿
        elsif is_ungulates? && params[:long_neck] && params[:long_legs] && params[:brown] && params[:dark_spots]
          @animal = "长颈鹿"
        # IF该动物是有蹄类动物 AND是白色 AND身上有黑色条纹 THEN该动物是斑马
        elsif is_ungulates? && params[:white] && params[:black_stripes]
          @animal = "斑马"
        end
      end
    elsif is_bird?
      @animal = "鸟类"
      # IF该动物是鸟 AND有不会飞AND有长腿 AND长脖子 AND是黑白色 THEN 该动物 是鸵鸟
      if is_bird? && params[:can_not_fly] && params[:long_legs] && params[:long_neck] && params[black_and_white]
        @animal = "鸵鸟"
      # IF该动物是鸟 AND不会飞 AND会游泳 AND是黑白色 THEN该动物是企鹅
      elsif is_bird? && params[:can_not_fly] && params[:can_swim] && params[:black_and_white]
        @animal = "企鹅"
      # IF该动物是鸟 AND善飞 AND不怕风浪 THEN该动物是信天翁
      elsif is_bird? && params[:good_at_fly] && params[:not_afraid_of_storms]
        @animal = "信天翁"
      end
    else
      @animal = "信息太少无法准确推断"
    end
  end

  private
    # 哺乳动物
    def is_mammal?
      params[:have_hair] || params[:have_milk]
    end

    # 鸟
    def is_bird?
      params[:have_feather] || (params[:can_fly] && params[:raw_eggs])
    end

    # 肉食动物
    def is_carnivore?
      (is_mammal? && params[:have_claws] && params[:have_canines] && params[:eyes_glued_to_the_front]) || (is_mammal? && params[:eat_meat])
    end

    # 蹄类动物
    def is_ungulates?
      is_mammal? && params[:have_ungulate]
    end

    # 偶蹄动物
    def is_artiodactyl?
      is_ungulates? && params[:cud]
    end
end

app/helpers/animal_behaviors_helper.rb
module AnimalBehaviorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/animal_behaviors/_form.html.erb
<%= form_for(@animal_behavior) do |f| %>
  <% if @animal_behavior.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@animal_behavior.errors.count, "error") %> prohibited this animal_behavior from being saved:</h2>

      <ul>
      <% @animal_behavior.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :behavior %><br>
    <%= f.text_field :behavior %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/animal_behaviors/edit.html.erb
<h1>Editing animal_behavior</h1>

<%= render 'form' %>

<%= link_to 'Show', @animal_behavior %> |
<%= link_to 'Back', animal_behaviors_path %>

app/views/animal_behaviors/index.html.erb
<h1>Listing animal_behaviors</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Behavior</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @animal_behaviors.each do |animal_behavior| %>
      <tr>
        <td><%= animal_behavior.code %></td>
        <td><%= animal_behavior.behavior %></td>
        <td><%= link_to 'Show', animal_behavior %></td>
        <td><%= link_to 'Edit', edit_animal_behavior_path(animal_behavior) %></td>
        <td><%= link_to 'Destroy', animal_behavior, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Animal behavior', new_animal_behavior_path %>

app/views/animal_behaviors/new.html.erb
<h1>New animal_behavior</h1>

<%= render 'form' %>

<%= link_to 'Back', animal_behaviors_path %>

app/views/animal_behaviors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @animal_behavior.code %>
</p>

<p>
  <strong>Behavior:</strong>
  <%= @animal_behavior.behavior %>
</p>

<%= link_to 'Edit', edit_animal_behavior_path(@animal_behavior) %> |
<%= link_to 'Back', animal_behaviors_path %>

app/views/index/index.html.erb
<div class="container">
  <h1>动物识别专家系统</h1>

  <h3>选择动物特性</h3>
  <%= form_tag('/index/index', method: :get) do %>
    <% @animal_behaviors.each do |ab| %>
      <div class="check-box-wrapper">
        <%= check_box_tag ab.code, ab.code, @checked_behaviors.key?(ab.code) %>
        <%= label_tag ab.code, ab.behavior %>
      </div>
    <% end %>
    <div class="btn-submit">
      <%= button_tag '提交' %>
      <%= button_tag '重置', id: "btn-reset" %>
    </div>
  <% end -%>

  <h3>识别结果</h3>
  <%= @animal %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AnimalIdentificationSystem</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>